//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Jabber.Net Library")]
[assembly: AssemblyDescription("Use .NET to connect to a Jabber chat service.")]
[assembly: AssemblyCompany("Kixeye, Inc")]
[assembly: AssemblyProduct("jabber.net")]
[assembly: AssemblyCopyright("Copyright (c) Kixeye, Inc 2013")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyDelaySign(false)]
[assembly: CLSCompliant(true)]

